apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  selector:
    app: simple-time-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service-deployment
  labels:
    app: simple-time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
      - name: simple-time-service
        image: docker.io/misterio77/simple_time_service
        ports:
        - containerPort: 8080
